# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'demandeEnvoyer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi
class cal_1(QtWidgets.QWidget):

    def __init__(self,qline):
        super().__init__()
        loadUi("cald.ui",self)
        self.qq = qline
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.pushButton.clicked.connect(self.Ok)
        self.calendarWidget.clicked.connect(self.printDateInfo)
        self.move(700,290)

    def printDateInfo(self):
        self.var = self.calendarWidget.selectedDate().toString("yyyy-MM-dd")
        self.qq.setText(self.var)
        return self.var

    def Ok(self):
        self.close()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = cal_1()
    ui.show()
    sys.exit(app.exec_())
