# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'demandeEnvoyer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi
class Ui_self_1(QtWidgets.QWidget):
    def fermer(self):
        self.close()
    def __init__(self):
        super().__init__()
        loadUi("demandeEnvoyer.ui",self)
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.setStyleSheet("""bacground-color : green;""")
        self.pushButton.clicked.connect(self.fermer)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_self_1()
    ui.show()
    sys.exit(app.exec_())
